version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
      resources:
        limits:
          memory: 768M
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  backend:
    build: .
    container_name: node_backend
    ports:
      - "3000:3000"
    environment:
      - ES_NODE=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local